Host: qgpu2010
Allocated GPU: 0
Starting C4 pre-training job...
INFO:__main__:Loading base model from local path: /home/iwm6052/adamus/FuncRoute-LM/gpt2-100m-custom
INFO:__main__:Loading training dataset 'c4' with streaming.
The repository for c4 contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/c4.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N] Traceback (most recent call last):
  File "/gpfs/home/iwm6052/adamus/FuncRoute-LM/pretrain.py", line 111, in <module>
    pretrain(args)
  File "/gpfs/home/iwm6052/adamus/FuncRoute-LM/pretrain.py", line 26, in pretrain
    train_dataset_stream = load_dataset(
  File "/home/iwm6052/.conda/envs/nlp/lib/python3.9/site-packages/datasets/load.py", line 2062, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/iwm6052/.conda/envs/nlp/lib/python3.9/site-packages/datasets/load.py", line 1782, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/iwm6052/.conda/envs/nlp/lib/python3.9/site-packages/datasets/load.py", line 1664, in dataset_module_factory
    raise e1 from None
  File "/home/iwm6052/.conda/envs/nlp/lib/python3.9/site-packages/datasets/load.py", line 1607, in dataset_module_factory
    return HubDatasetModuleFactoryWithScript(
  File "/home/iwm6052/.conda/envs/nlp/lib/python3.9/site-packages/datasets/load.py", line 1264, in get_module
    trust_remote_code = resolve_trust_remote_code(self.trust_remote_code, self.name)
  File "/home/iwm6052/.conda/envs/nlp/lib/python3.9/site-packages/datasets/load.py", line 137, in resolve_trust_remote_code
    raise ValueError(
ValueError: The repository for c4 contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/c4.
Please pass the argument `trust_remote_code=True` to allow custom code to be run.
Job finished with exit code 1
